#!/usr/bin/env bash
# Tests for scripts/render_bank_topology.py (ADR-BANK-TOPOLOGY-03 projections).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
GEN="$ROOT/scripts/render_bank_topology.py"
FAIL=0

ok() { echo "PASS: $1"; }
bad() { echo "FAIL: $1"; FAIL=1; }

# 1. Real registry renders and counts every agent row.
OUT="$(python3 "$GEN" --registry "$ROOT/docs/governance/AGENT-REGISTRY-BANK-MASTER-2026-07-22.md")"
EXPECTED=$(grep -c '^| AG-' "$ROOT/docs/governance/AGENT-REGISTRY-BANK-MASTER-2026-07-22.md")
grep -q "agents: \*\*${EXPECTED}\*\*" <<<"$OUT" \
  && ok "counts all ${EXPECTED} registry rows" \
  || bad "agent count mismatch (expected ${EXPECTED})"

# 2. Reserved-control rooms are marked and drawn WITHOUT a command edge.
grep -q "F3_aml.*RESERVED CONTROL" <<<"$OUT" \
  && ok "F3-aml marked reserved-control" || bad "F3-aml not marked"
grep -qE "F3 -\.-> F3_aml" <<<"$OUT" \
  && ok "reserved-control room uses non-command edge" || bad "reserved room drawn as command edge"
grep -qE "F2 --> F2_payments" <<<"$OUT" \
  && ok "ordinary room keeps command edge" || bad "ordinary room edge missing"

# 3. Output is self-labelled as generated (never hand-edited canon).
grep -q "GENERATED by" <<<"$OUT" && ok "output declares itself generated" || bad "missing generated banner"

# 4. Malformed registry fails loudly instead of rendering a half-truth.
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
printf '| AG-X1 | short | row |\n' > "$TMP/bad.md"
if python3 "$GEN" --registry "$TMP/bad.md" >/dev/null 2>&1; then
  bad "malformed row accepted"
else
  ok "malformed row rejected (fail-loud)"
fi

# 5. Empty registry is an error, not an empty diagram.
printf '# nothing here\n' > "$TMP/empty.md"
if python3 "$GEN" --registry "$TMP/empty.md" >/dev/null 2>&1; then
  bad "empty registry accepted"
else
  ok "empty registry rejected"
fi

# 6. --out writes the file.
python3 "$GEN" --registry "$ROOT/docs/governance/AGENT-REGISTRY-BANK-MASTER-2026-07-22.md" \
  --out "$TMP/report.md" >/dev/null
[ -s "$TMP/report.md" ] && ok "--out writes report" || bad "--out produced nothing"

exit $FAIL
